version: '3'

services:
  mysql:
    image: mysql:8.0.31
    container_name: sim-mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: sim
        MYSQL_USER: sim
        MYSQL_PASSWORD: 1234